version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  certbot_init:
    image: certbot/certbot
    container_name: certbot_init
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot \
             -d beez.pp.ua \
             --email your@email.com \
             --agree-tos \
             --non-interactive

  certbot:
    image: certbot/certbot
    container_name: certbot_renew
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew --webroot -w /var/www/certbot --quiet;
               sleep 12h;
             done"
