name: Deploy to VM

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script_stop: true
          script: |
            set -euxo pipefail

            APP_DIR="${{ secrets.APP_DIR }}"
            REPO_URL="https://github.com/${{ github.repository }}.git"
            BRANCH="main"

            mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            if [[ ! -d ".git" ]]; then
              git init
              git remote add origin "$REPO_URL" || true
            fi

            git fetch --depth=1 origin "$BRANCH"
            git checkout -B "$BRANCH" "origin/$BRANCH"

            printf "%s" "${{ secrets.APP_ENV }}" > .env
            chmod 600 .env

            docker-compose down || true
            docker-compose up -d --build

            docker-compose ps
