version: "3.8"

services:
  app:
    build:
      context: .      
      dockerfile: src/Dockerfile
    container_name: fastapi_app
    restart: always
    expose:
      - "8000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - web

networks:
  web:
    driver: bridge
