name: Deploy FastAPI to VPS

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name (optional)'
        required: false
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add beez.pp.ua to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan beez.pp.ua >> ~/.ssh/known_hosts

      - name: Copy files
        run: |
          rsync -avz --delete \
            --exclude certbot/conf \
            ./ azureuser@beez.pp.ua:/home/azureuser/Back

      - name: Rebuild and restart docker-compose
        run: |
          ssh azureuser@beez.pp.ua <<'EOF'
            cd /home/azureuser/Back
            docker compose down
            docker compose up -d --build
          EOF
