name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan beez.pp.ua >> ~/.ssh/known_hosts

    - name: Sync files to VPS
      run: |
        rsync -avz --delete --exclude certbot/conf ./ azureuser@beez.pp.ua:/home/azureuser/Back

    - name: Restart Docker Compose on VPS
      run: |
        ssh azureuser@beez.pp.ua << 'EOF'
          cd /home/azureuser/Back
          docker compose down
          docker compose up -d --build --remove-orphans
          echo "⏳ Waiting for FastAPI to be ready..."
          for i in {1..10}; do
            if curl -sSf http://localhost:8000/docs > /dev/null; then
              echo "✅ FastAPI is up!"
              break
            fi
            echo "Waiting..."
            sleep 5
          done
        EOF
